server:
  port: 16102

spring:
  application:
    name: user-service
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:16001/eureka/

feign:
  hystrix:
    enabled: true

xinruke:
  commodity:
    enabled: true
    config: a,b,c,1,2,3
