server:
  port: 8762

spring:
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/

feign:
  hystrix:
    enabled: true
