server:
  port: 16000

spring:
  application:
    name: zuul-service
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:16001/eureka/
zuul:
  routes:
    user:
      path: /userZuul/**
      serviceId: user-service
  ignored-services: '*' #设置不自动创建该服务的默认路由。禁用所有：'*'