server:
  port: 8761

spring:
  application:
    name: eureka-service

# Eureka的访问路径：http://localhost:8761/
eureka:
  client:
    fetch-registry: false #是否检索服务
    register-with-eureka: false #是否向服务注册中心注册自己
    service-url: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  file: logs/study_eureka.log
  file.max-history: 10
  file.max-size: 100MB
  level:
    root: info
  path: logs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
